### ISSUE TITLE
Consider grid layout for "directories & files"

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-navigator#55]
Instead of using flex, we may want to implement the grid using CSS grid, so we can have equidistant spacing and have items wrap as expected. (Using flex would mean that all items would have equidistant spacing if we changed the spacing model.) Additionally, we should be using gap, not margin, to space out items. We could also have no gap/margin, but there's probably some value in having some gutter space to deselect an item (and perhaps add canvas-style selection later on).

For example, something like this would change the spacing to rely on a grid. (We'd want to refactor it to adapt to this kind of layout, not override the PF React "Flex" as this would do. Note: PatternFly's "Grid" layout is not CSS grid; it's mainly a 12-cell design grid like Bootstrap uses, not a CSS grid as I'm suggesting here. That said, the PF Grid layout for "smart (reponsive)" may work as a basis for this... but it does a bunch of nonsense things that might also get in the way).

```scss
#folder-view {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr));
    justify-items: baseline;
}

.file-item,
.directory-item {
    margin: 0;
}
```
